os:
  - linux
  - osx

language: cpp

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - git clone https://github.com/smealum/ctrulib

install:
  - sudo perl devkitARMupdate.pl
  - cd ctrulib/libctru
  - make
  - sudo make install

script:
  - make
